### ISSUE TITLE
Criar uma secção de Execution no readme.md

### ISSUE THREAD

**Issue by InSebas** [MiguelArroz/pariaula12B-equipa3#1]
@davidjos1 @MiguelArroz @angeloAP  podem adicionar uma secção pff? 
inventem qualquer coisa

**Comment by angeloAP** [comment]
.opçli,ukyjthygrerfewdqswa

**Comment by davidjos1** [comment]
o Arroz que trabalhe que não tem RI

**Comment by MiguelArroz** [comment]
Vamos lá ver...ahaha

**Comment by MiguelArroz** [comment]
[https://tenor.com/search/geek-gifs](url)
